import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // The account avatar is generated by DiceBear. `Avatar` currently
    // renders it with `unoptimized`, so this entry is only needed if you
    // switch it to the optimized image pipeline.
    remotePatterns: [
      {
        protocol: "https",
        hostname: "api.dicebear.com",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;
